import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import TanStackProvider from '@/components/providers/TanStackProvider'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <TanStackProvider>
          {children}
          <Toaster />
        </TanStackProvider>
      </body>
    </html>
  )
}
